version: '3'
services:
  moodle:
    image: jorarmarfin/moodle:3.11.10
    container_name: srv-moodle-apache
    volumes:
      - ./backup:/backup
    ports:
      - 9001:80
    restart: always
    environment:
      - DB_HOST=DB
      - DB_NAME=moodle
      - DB_USER=root
      - DB_PASS=root
      - MOODLE_DOMAIN=localhost:9001
    networks:
      - net-moodle
  db:
    container_name: srv-moodle-mysql
    image: jorarmarfin/mysql:5.7-moodle-3.11.10
    environment:
      - MYSQL_ROOT_PASSWORD=root
      # - MYSQL_DATABASE=moodle
    restart: always
    networks:
      - net-moodle
  adminer:
    container_name: srv-moodle-adminer
    image: adminer:latest
    ports:
      - 9002:8080
    restart: always
    networks:
      - net-moodle
networks:
  net-moodle:
